plugins:
  - github
  - jest
  - prettier
extends:
  - plugin:github/recommended
  - plugin:github/typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
ignorePatterns:
  - 'node_modules'
  - 'dist'
  # Configuration files in the root directory
  - '*.js'
rules:
  curly: error
  no-console: warn
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
      ignoreRestSiblings: true
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  filenames/match-regex: off
env:
  node: true
  jest/globals: true
